openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: This is a sample server for an e-commerce API.

tags:
  - name: orders
    description: Operations about orders

paths:
  /api/orders:
    get:
      tags:
        - orders
      summary: Get orders
      description: Get the orders
      operationId: getOrders
      responses:
        '200':
          description: The orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orders'
    post:
      tags:
        - orders
      summary: Add order
      description: Add an order
      operationId: addOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                shippingInfo:
                  $ref: '#/components/schemas/Shipping'
                paymentInfo:
                  $ref: '#/components/schemas/Payment'
      responses:
        '200':
          description: Order added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
  /api/orders/{id}:
    get:
      tags:
        - orders
      summary: Get order by id
      description: Get an order by id
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          description: ID of the order to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    put:
      tags:
        - orders
      summary: Update order
      description: Update an order
      operationId: updateOrder
      parameters:
        - name: id
          in: path
          description: ID of the order to update
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum:
                    - pending
                    - processing
                    - shipped
                    - delivered
                    - cancelled
      responses:
        '200':
          description: Order updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    delete:
      tags:
        - orders
      summary: Delete order
      description: Delete an order
      operationId: deleteOrder
      parameters:
        - name: id
          in: path
          description: ID of the order to delete
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

components:
  schemas:
    Order:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        totalAmount:
          type: number
        status:
          type: string
          enum:
            - pending
            - processing
            - shipped
            - delivered
            - cancelled
        payment:
          type: string
        shipping:
          type: string
    OrderItem:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: number
        price:
          type: number
        totalPrice:
          type: number
    Orders:
      type: array
      items:
        $ref: '#/components/schemas/Order'
    Payment:
      type: object
      properties:
        paymentMethod:
          type: string
          enum:
            - creditCard
            - debitCard
            - paypal
    Shipping:
      type: object
      properties:
        shippingAdress:
          type: object
          properties:
            address:
              type: string
            city:
              type: string
            state:
              type: string
            zipCode:
              type: string
        shippingMethod:
          type: string
          enum:
            - standard
            - express