openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: This is a sample server for an e-commerce API.

tags:
  - name: users
    description: Operations about users

paths:
  /api/users/register:
    post:
      tags:
        - users
      summary: Register a new user
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: string
                example: User registered successfully
  /api/users/login:
    post:
      tags:
        - users
      summary: Login a user
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User logged in successfully
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      _id:
                        type: integer
                      name:
                        type: string
                      email:
                        type: string
                      role: 
                        type: string
  /api/users/logout:
    post:
      tags:
        - users
      summary: Logout a user
      operationId: logoutUser
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
                example: User logged out successfully